### ISSUE TITLE
P1

### ISSUE THREAD

**Issue by pujiaxun** [Servon-Lee/web_tasks#1]
数据精度并不够呀～

我一开始调试的时候long也会溢出，不知道在C++里面用什么，希望学长能够指点一下~~
下面是Java代码：

import java.math.BigInteger;

public class Fibonacci {

public static void main(String[] args) {
	BigInteger a = BigInteger.ONE;
	BigInteger b = BigInteger.ONE;
	for (int i = 0; i < 50; i++) {
		System.out.print(a + " " + b + " ");
		a = a.add(b);
		b = a.add(b);
	}
}
}

**Comment by zewenli98** [comment]
我一开始调试的时候long也会溢出，不知道在C++里面用什么，希望学长能够指点一下~~
下面是Java代码：

import java.math.BigInteger;

public class Fibonacci {

	public static void main(String[] args) {
		BigInteger a = BigInteger.ONE;
		BigInteger b = BigInteger.ONE;
		for (int i = 0; i < 50; i++) {
			System.out.print(a + " " + b + " ");
			a = a.add(b);
			b = a.add(b);
		}
	}

}

**Comment by pujiaxun** [comment]
尝试过手动实现加法吗？
Servon-Lee <notifications@github.com>于2017年6月27日 周二22:02写道：
